### ISSUE TITLE
Small bug about VARopt.m

### ISSUE THREAD

**Issue by lnsongxf** [LRondina/VAR_toolbox#1]
Hi Luca,
I emailed you about this problem before, and now I open an issue to mark it, so you can fix it in the future, you don't need to reply,

The file VARirplot.m has a "savefigs = VARopt.savefigs", but the VARopt.m file doesn't have "VARopt.savefigs", so when we want to plot a figure, we will encounter an error, after adding one line "VARopt.savefigs  = true/false;  % strings indicate saving fig or not as default", this problem solved (of course).

Really appreciate your work on this Toolbox,

Best,
Xiaofei

**Comment by LRondina** [comment]
Hi @lnsongxf !

Thanks for pointing that out. Feel free to fork this repo and open a pull request. I will review it and merge it.

**Comment by lnsongxf** [comment]
Hi @LRondina ，

Thank for your reply, I have opened a pull request,

You can review it and decide whether to merge it or not.

Best,
Xiaofei

**Comment by LRondina** [comment]
Thanks for your pull request. I have merged it into master. See [#2](https://github.com/LRondina/VAR_toolbox/pull/2)
